final List<String> changePalaceFilterButton = [
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Corso Trieste',
  'Via Pitagora',
  'Viale Bruno Buozzi 18',
  'Viale Bruno Buozzi 18',
  'Viale Bruno Buozzi 18',
];
