name: adminpanel
description: ""

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_settings: ^4.2.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter_app_badger: ^1.5.0
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^13.0.0
  http_parser: ^4.0.2
  image_picker: ^0.8.6+1
  image_picker_ios: ^0.8.6+1
  intl: ^0.18.0
  package_info_plus:
  path_provider: ^2.0.12
  photo_view: ^0.14.0
  provider: ^6.0.5
  readmore: ^2.2.0
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.17
  smooth_page_indicator: ^1.0.0+2
  status_alert: ^1.0.1
  tap_debouncer: ^2.0.2
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  
dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  # flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/