name: adminpanel
description: ""

publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_settings: ^5.1.1
  cupertino_icons: ^1.0.5
  dio: ^5.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  firebase_core_web: ^2.3.0
  firebase_messaging_web: ^3.3.0
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^15.1.1
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  image_picker_ios: ^0.8.6+1
  intl: ^0.18.0
  package_info_plus:
  path_provider: ^2.0.12
  photo_view: ^0.14.0
  provider: ^6.0.5
  readmore: ^2.2.0
  rxdart: ^0.27.7
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.17
  signature: ^5.4.0
  smooth_page_indicator: ^1.0.0+2
  status_alert: ^1.0.1
  tap_debouncer: ^2.0.2
  timeago: ^3.5.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7

  # Geocoding
  geolocator: ^10.1.0
  location: ^5.0.0
  permission_handler: ^11.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  #   flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/misc/