name: adminpanel
description: ""

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_html: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  images_picker: ^1.2.11
  flutter_inappwebview: ^5.7.2+2
  modal_bottom_sheet: ^2.1.2
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  status_alert: ^1.0.1
  
dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/